{
 "title": "Race-of-Sloths dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "selectedApp", "label": "Selected app", "query": "race-of-sloths, ros-staging" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event success rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(bot_event_total{success=\"1\", app=\"$selectedApp\"}[24h])) * 100) / sum(increase(bot_event_total{app=\"$selectedApp\"}[24h]))",
     "legendFormat": "Success rate"
    }
   ]
  },
  {
   "title": "Server 200 rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rocket_http_requests_total{status=\"200\",app=\"$selectedApp\"}[24h])) / sum(increase(rocket_http_requests_total{app=\"$selectedApp\"}[24h])) * 100",
     "legendFormat": "Success rate"
    }
   ]
  },
  {
   "title": "Daily events activity (aggregated by hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(bot_event_total{app=\"$selectedApp\"}[1h]))",
     "legendFormat": "Activity"
    }
   ]
  },
  {
   "title": "Server requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(rocket_http_requests_total{endpoint!=\"/metrics\", app=\"$selectedApp\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(endpoint, method) (increase(rocket_http_requests_total{endpoint!=\"/metrics\"}[5m]))",
     "legendFormat": "{{method}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Bot execution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (event_type)(bot_event_processing_time_sum{app=\"$selectedApp\"}[5m])/sum by (endpoint)(bot_event_processing_time_count{app=\"$selectedApp\"}[5m])",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Request processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (endpoint)(rocket_http_requests_duration_seconds_sum{endpoint!=\"/metrics\", app=\"$selectedApp\"}[5m])/sum by (endpoint)(rocket_http_requests_duration_seconds_count{endpoint!=\"/metrics\", app=\"$selectedApp\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Most active users",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by(author) (increase(bot_event_total{success='1', app=\"$selectedApp\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Github rate limit usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_api_read_requests{app=\"$selectedApp\"}",
     "legendFormat": "Total requests"
    },
    {
     "expr": "increase(github_api_write_requests_total{app=\"$selectedApp\"}[1m])",
     "legendFormat": "Write per minute"
    },
    {
     "expr": "increase(github_api_write_requests_total{app=\"$selectedApp\"}[1h])",
     "legendFormat": "Write per hour"
    }
   ]
  },
  {
   "title": "Failed events",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event_type)(increase(bot_event_total{success!='1', app=\"$selectedApp\"}[24h])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed events daily",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event_type) (increase(bot_event_total{app=\"$selectedApp\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most active repos",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(organization, repository) (increase(bot_event_total{success=\"1\", app=\"$selectedApp\"}[24h])))",
     "legendFormat": "{{organization}}/{{repository}}"
    }
   ]
  }
 ]
}